# CMU 15-712, Software Systems
year = 2026
term = "Fall Semester"

meets = ["mon", "wed", "fri"]
starts = "12:30"
ends = "13:50"
location = "GHC 4303"

first_day = "2026-08-24"
last_day = "2026-12-03"

[[exam.final]]
name = "Final Exam"
date = "TBD"

[[exam.midterm]]
name = "Midterm Exam"
date = "TBD"

[[instructor]]
name = "David G. Andersen"
email = "dga@cs.cmu.edu"
webpage = "https://www.cs.cmu.edu/~dga/"
office = "GHC 9109"
hours = "By Appointment"

[[instructor]]
name = "Ziyue Qiu"
email = "ziyueqiu@andrew.cmu.edu"
webpage = "https://ziyueqiu.github.io/"
office = "GHC 5007"
hours = "TBA"

[[holiday]]
dates = ["2026-09-07"]
name = "Labor Day"

[[holiday]]
dates = ["2026-10-12", "2026-10-13", "2026-10-14", "2026-10-15", "2026-10-16"]
name = "Fall Break"

[[holiday]]
dates = ["2026-11-25", "2026-11-27", "2026-11-27"]
name = "Thanksgiving Break"

[[holiday]]
dates = ["2026-11-23"]
name = "Early Thanksgiving Break"

[[holiday]]
dates = ["2026-09-21"]
name = "Yom Kippur"

[[lecture]]
title = "Introduction"
notes = "Wisdom papers"
instructor = "dga"

[[lecture.papers]]
title = "KeshavHowToRead"
link = "HowtoReadPaper.pdf"

[[lecture.papers]]
title = "StentHowToRead"
link = "howtoreadacspaper.pdf"

[[lecture.papers]]
title = "LevisHowToRead"
link = "reading-levis.pdf"

[[lecture.papers]]
title = "Hamming86"
link = "hamming86.pdf"

[[lecture.papers]]
title = "Lampson83"
link = "lampson83.pdf"

[[lecture]]
section_header = "Part 1: Concurrency, Threads, Parallelism, Ordering, and Races"
title = "Implementing remote procedure calls"
notes = "SigOps HoF paper"
instructor = "dga"

[[lecture.papers]]
title = "Saltzer84"
link = "saltzer84.pdf"

[[lecture.papers]]
title = "Birrell84"
link = "birrell84.pdf"

[[lecture.papers]]
title = "Chen2023"
link = "https://www.usenix.org/system/files/nsdi23-chen-jingrong.pdf"

[[lecture]]
title = "Ensō: A Streaming Interface for NIC-Application Communication"
notes = "OSDI '23 Best Paper"
instructor = "dga"

[[lecture.papers]]
title = "Sadok23"
link = "https://www.usenix.org/system/files/osdi23-sadok.pdf"

[[lecture]]
title = "Using Threads in Interactive Systems: A Case Study"
instructor = "dga"

[[lecture.papers]]
title = "Hauser93"
link = "hauser93.pdf"

[[lecture]]
title = "Time, Clocks, and the Ordering of Events in a Distributed System"
notes = "SigOps HoF paper"
instructor = "dga"

[[lecture.papers]]
title = "Lamport78"
link = "lamport78.pdf"

[[lecture]]
section_header = "Part 2: More bugs than a bait store"
title = "Eraser: A Dynamic Data Race Detector for Multi-Threaded Programs"
notes = "SOSP'97 best paper. <a href='http://www.stanford.edu/~engler/deviant-sosp-01.pdf'>Bugs as Deviant Behavior</a> (SOSP'01)."
instructor = "dga"

[[lecture.papers]]
title = "Savage97"
link = "savage97.pdf"

[[lecture]]
title = "IronFleet: Proving Practical Distributed Systems Correct"
notes = "A <a href='https://blog.acolyer.org/2015/10/15/ironfleet-proving-practical-distributed-systems-correc/'>discussion in The Morning Paper</a>."
instructor = "dga"

[[lecture.papers]]
title = "Hawblitzel15"
link = "https://www.andrew.cmu.edu/user/bparno/papers/ironfleet.pdf"

[[lecture]]
section_header = "Part 3: File Systems and Disks"
title = "AFS"
notes = "<a href='http://portal.acm.org/citation.cfm?id=74850.74870'>Leases paper</a>. SigOps HoF papers"
instructor = "dga"

[[lecture.papers]]
title = "Howard88"
link = "howard88.pdf"

[[lecture]]
title = "The Design and Implementation of a Log-Structured File System"
notes = "SigOps HoF paper."
instructor = "dga"

[[lecture.papers]]
title = "Rosenblum92"
link = "rosenblum92.pdf"

[[lecture]]
title = "A Case for Redundant Arrays of Inexpensive Disks (RAID)"
notes = "SigOps HoF paper. Fast'07 best paper."
instructor = "dga"

[[lecture.papers]]
title = "Patterson88"
link = "patterson88.pdf"

[[lecture.papers]]
title = "Schroeder07"
link = "http://www.pdl.cmu.edu/PDL-FTP/Failure/failure-fast07.pdf"

[[lecture]]
section_header="Part 4: Big Data Systems"
title="MapReduce and Ray"
notes="SigOps HoF paper. For more see Spark, Nyad, and <a href='http://research.microsoft.com/en-us/projects/dryad/eurosys07.pde'>Dryad</a>."
instructor = "dga"

[[lecture.papers]]
title = "Dean04"
link = "dean04.pdf"

[[lecture.papers]]
title="Moritz18"
link="https://www.usenix.org/system/files/osdi18-moritz.pdf"

#[[lecture.papers]]
#title="Zaharia12"
#link="https://www.usenix.org/system/files/conference/nsdi12/nsdi12-final138.pdf"

[[lecture]]
title = "DBOS: A DB-oriented Operating System"
instructor = "dga"

[[lecture.papers]]
title = "DBOS"
link = "https://people.eecs.berkeley.edu/~matei/papers/2022/vldb_dbos.pdf"

#[[lecture]]
#title="TensorFlow: Large-Scale Machine Learning on Heterogeneous Distributed Systems"

#[[lecture.papers]]
#title="TensorFlow"
#link="http://download.tensorflow.org/paper/whitepaper2015.pdf"

[[lecture]]
section_header = "Part 5: Kernels and Parallelism"
title = "OS Architecture and Extensibility: SPIN and the Exokernel"
notes = "SOSP'97 paper. SigOps HoF paper. <a href='http://www.cs.cmu.edu/~15712/papers/engler95.pdf'>Original Exokernel paper</a> <a href='https://www.sigops.org/s/conferences/sosp/2009/papers/baumann-sosp09.pdf'>Multikernel</a> (SOSP'09)."
instructor = "dga"

[[lecture.papers]]
title = "Bershad95"
link = "https://www.cs.cmu.edu/afs/cs.cmu.edu/academic/class/15712-s12/www/papers/bershad95.pdf"

[[lecture.papers]]
title = "Kaashoek97"
link = "kaashoek97sosp.pdf"

[[lecture]]
title="Fault Tolerance: Primary-Backup State Machine Replication"
instructor = "dga"

[[lecture.papers]]
title="VMFT"
link="http://nil.csail.mit.edu/6.824/2022/papers/vm-ft.pdf"

[[lecture]]
title="Paxos"
notes="<a href='http://en.wikipedia.org/wiki/Paxos_algorithm'>Wikipedia Paxos article</a>. <a href='http://research.microsoft.com/users/lamport/pubs/lamport-paxos.pdf'>Lamport's original Greek parable</a> <a href='http://lamport.azurewebsites.net/pubs/pubs.html#lamport-paxos'>Lamport's comments on original paper.</a>."
instructor = "dga"

[[lecture.papers]]
title="Lamport01"
link="paxos-simple.pdf"

#[[lecture]]
#title="Dynamo: Amazon's Highly Available Key-value Store"

#[[lecture.papers]]
#title="DeCandia07"
#link="decandia07.pdf"

[[lecture]]
title="Midterm Review (no lecture)"
notes="You're welcome to use the classroom or do this on your own, dga will not be there."


[[lecture]]
title="Project Discussions (in class)"

[[lecture]]
title = "Midterm 1"

[[lecture]]
title = "Project Discussions with Staff"

[[lecture]]
title="Project Discussions with Staff"

[[lecture]]
title = "The Scalable Commutativity Rule: Designing Scalable Software for Multicore Processors"
notes = "SOSP'13 best paper"
instructor = "dga"

[[lecture.papers]]
title = "Clements13"
link = "clements13.pdf"

[[lecture]]
title = "No class"

[[lecture]]
section_header = "Part 6: Transactions and Databases"
title = "On Optimistic Methods for Concurrency Control"
notes = "SigOps HoF paper. <a href='http://www.cs.cmu.edu/~dga/15-849/papers/speculator-sosp2005.pdf'>Spectulative Execution in a Distributed File System</a> <a href='http://www.cs.cmu.edu/~15712/papers/Lehman81.pdf'>Efficient Locking for Concurrent Operations on B-Trees</a>"
instructor = "dga"

[[lecture.papers]]
title = "Kung81"
link = "kung81.pdf"

[[lecture]]
title = "No class"

[[lecture]]
title = "Project Meetings (all day)"

[[lecture]]
title="Concurrency Control and Recovery"
notes="<a href='http://www.cs.cmu.edu/~15712/papers/bernstein83.pdf'>Bernstein's concurrency notes - MVCC</a>, <a href='http://www.cs.cmu.edu/~15712/papers/bailis14.pdf'>Coordination Avoidance</a>"
instructor = "dga"

[[lecture.papers]]
title = "Franklin97"
link = "franklin97concurrency.pdf"

[[lecture]]
title = "No class"

[[lecture]]
section_header = "Part 7: Generalized Fault Tolerance and Security"
title = "The Byzantine Generals Problem"
notes = "<a href='http://research.microsoft.com/en-us/um/people/lamport/pubs/pubs.html#byz'>Lamport's comments on the Byzantine Generals paper.</a>"
instructor = "dga"

[[lecture.papers]]
title = "Lamport82"
link = "lamport82.pdf"

[[lecture.papers]]
title = "Castro99"
link = "castro99.pdf"

[[lecture]]
title = "No class"

[[lecture]]
title = "Reflections on Trusting Trust, Why Cryptosystems Fail, Crisis and Aftermath"
notes = "SigOps HoF paper. Write Summary only for Anderson94."
instructor = "dga"

[[lecture.papers]]
title = "Thompson84"
link = "p761-thompson.pdf"

[[lecture.papers]]
title = "Anderson94"
link = "anderson94.pdf"

[[lecture.papers]]
title = "Spafford89"
link = "Spafford89.pdf"

[[lecture]]
title = "No class."

[[lecture]]
title = "No Class"

[[lecture]]
title = "Highlights from the SOSP15 History Day Talks"
notes = "<a href='https://www.sigops.org/s/conferences/sosp/2015/history/'>SOSP15 History Day.</a>"

[[lecture]]
title = "Effective Presentations"

[[lecture.papers]]
title="Ware24"
link="effective_presentations.pdf"

[[lecture.papers]]
title="PLMW24"
link="PLMW-talk-opinionated.pdf"

[[lecture]]
title = "Project Presentations"

[[lecture]]
title = "Project Presentations"

[[lecture]]
title = "Midterm 2, Date Time And Location TBA"

[[post_class_event]]
date = "2026-12-04"
title = "Final Report Due by 11:59pm"
